<link rel="stylesheet" href="/bbps/css/customs.css" type="text/css">

<div class="wrapper00">
    <div class="container">
    <div class="page-header">
			<h4>BBPS FAQs</h4>
			<div class="fieldstx closetab">
                    <a class="btn btn-default" href="javascript:void(0)">Back</a>
			</div>
		</div>
    <div class="panel-group faq-group" id="faqlist" role="tablist">
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he1">
			  <h4 class="panel-title">
				<a role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq1" aria-expanded="true" aria-controls="faq1">
				  What is BBPS?
				</a>
			  </h4>
			</div>
			<div id="faq1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="he1">
			  <div class="panel-body">
				<p>Bharat Bill Payment System (BBPS) is a Reserve Bank of India (RBI) system driven by National Payments Corporation of India (NPCI) that offers interoperable and accessible bill payment service to consumers via digital (bank channels) as well as through a network of agents & bank branches. </p>
				<p>Airpay is bringing the same services on its platform to enable businesses to pay their bills in a easy and time saving manner. </p>
			  </div>
			</div>
		  </div>
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he2">
			  <h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq2" aria-expanded="false" aria-controls="faq2">
				  What benefits will I get from airpay’s BBPS service?
				</a>
			  </h4>
			</div>
			<div id="faq2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="he2">
			  <div class="panel-body">
				<p>Ans You can manage and pay your bills from a common dashboard.  Select and pay multiple bills at once with a single click. Receive notifications on partnerpay for bill payments before due date to avoid late payment fees from your service provide. </p>
			  </div>
			</div>
		  </div>
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he3">
			  <h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq3" aria-expanded="false" aria-controls="faq3">
				  What bills can I pay?
				</a>
			  </h4>
			</div>
			<div id="faq3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="he3">
			  <div class="panel-body">
				<p>You can clear repetitive payments for everyday utility services such as electricity, water, gas, telecom (mobile postpaid, landline postpaid, broadband) and Direct-to-Home (DTH). More services will be enabled with time. </p>
			  </div>
			</div>
		  </div>
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he4">
			  <h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq4" aria-expanded="false" aria-controls="faq4">
				  How can I update the accounts for which I have to pay?
				</a>
			  </h4>
			</div>
			<div id="faq4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="he4">
			  <div class="panel-body">
				<p><strong>Open your dashboard -> Select BBPS -> Select Utility Type -> Select Biller. </strong></p>
				<p>Upload the excel file to add accounts into airpay’s system. Use Sample format available for download for each type of utility as a reference. Once uploaded, airpay will query and add the accounts to your dashboard. You can make changes i.e add or remove them from your billing cycle. Except the first time, Airpay will auto fetch the bills against respective account as and when they are generated by your service provider. </p>
			  </div>
			</div>
		  </div>
		  
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he5">
			  <h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq5" aria-expanded="false" aria-controls="faq5">
				  How do I make payments to pay for the bills?
				</a>
			  </h4>
			</div>
			<div id="faq5" class="panel-collapse collapse" role="tabpanel" aria-labelledby="he5">
			  <div class="panel-body">
				<p>Select the accounts for which you wish to make payments. Currently, multiple account selection is allowed only under respective billers i.e one can select, say, multiple Vodafone numbers to pay but NOT across Vodafone and Airtel to make payments. </p>
				<p>Preferred method of payment is Merchant Wallet as there are no charges applicable for bill payment</p>
				<p>After selecting the accounts -> Click Pay -> Complete transaction on airpay’s payment page</p>
				<p>After payment, airpay will update the invoices with the reference numbers for bill paid as shared by your service provider. You can utilize the reference number for any communication with your service provider</p>
			  </div>
			</div>
		  </div>
		  
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he6">
			  <h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq6" aria-expanded="false" aria-controls="faq6">
				  Are there any charges for bill payments?
				</a>
			  </h4>
			</div>
			<div id="faq6" class="panel-collapse collapse" role="tabpanel" aria-labelledby="he6">
			  <div class="panel-body">
				<p>All bills are to be paid at the actual amount billed. Additional transaction charges + taxes are applicable as per the payment instrument selected. We recommend use Merchant Wallet as there are no transactions applicable for this instrument. No service charges are levied by airpay. </p>
			  </div>
			</div>
		  </div>
		  
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he7">
			  <h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq7" aria-expanded="false" aria-controls="faq7">
				  How do I know a bill is paid?
				</a>
			  </h4>
			</div>
			<div id="faq7" class="panel-collapse collapse" role="tabpanel" aria-labelledby="he7">
			  <div class="panel-body">
				<p>All paid bills will be visible under the Paid Bills section. You can download the invoices for the bills paid anytime.</p>
			  </div>
			</div>
		  </div>
		  
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he8">
			  <h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq8" aria-expanded="false" aria-controls="faq8">
				 What happens if the bill doesn’t get paid?
				</a>
			  </h4>
			</div>
			<div id="faq8" class="panel-collapse collapse" role="tabpanel" aria-labelledby="he8">
			  <div class="panel-body">
				<p>In case a bill doesn’t get paid for whatsoever reason, the refund will automatically reflect in your merchant wallet within 48 Hours of bill payment. Airpay frequently queries the various billers throughout the day to update the status of your bill payment. </p>
			  </div>
			</div>
		  </div>
		  
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he8">
			  <h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq8" aria-expanded="false" aria-controls="faq8">
				 What happens if the bill doesn’t get paid?
				</a>
			  </h4>
			</div>
			<div id="faq8" class="panel-collapse collapse" role="tabpanel" aria-labelledby="he8">
			  <div class="panel-body">
				<p>In case a bill doesn’t get paid for whatsoever reason, the refund will automatically reflect in your merchant wallet within 48 Hours of bill payment. Airpay frequently queries the various billers throughout the day to update the status of your bill payment. </p>
			  </div>
			</div>
		  </div>
		  
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he9">
			  <h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq9" aria-expanded="false" aria-controls="faq9">
				 Can I use my refund amount to pay the next bill?
				</a>
			  </h4>
			</div>
			<div id="faq9" class="panel-collapse collapse" role="tabpanel" aria-labelledby="he9">
			  <div class="panel-body">
				<p>Yes! You can use the funds in your merchant wallet to pay any other bill or the same bill. </p>
			  </div>
			</div>
		  </div>
		  
		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="he10">
			  <h4 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#faqlist" href="#faq10" aria-expanded="false" aria-controls="faq10">
				 Can I get a refund for a bill paid successfully?
				</a>
			  </h4>
			</div>
			<div id="faq10" class="panel-collapse collapse" role="tabpanel" aria-labelledby="he10">
			  <div class="panel-body">
				<p>Sorry, there is no provision to un-do a bill payment. Please ensure you input the correct account number/phone numbers/customer ID/etc. while uploading the bulk document. Airpay will be not be liable to make any refunds for any bill unintentionally successfully paid.  </p>
			  </div>
			</div>
		  </div>
		  
		</div>
		<p>Have more questions? Reach out to us at – techsupport@airpay.co.in</p>
    </div>
    </div>
</div>