<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%group_invoice_map}}".
 *
 * @property integer $GROUP_INVOICE_MAP_ID
 * @property integer $GROUP_INVOICE_ID
 * @property integer $INVOICE_ID
 * @property string $UTR_NO
 * @property string $BRAND
 * @property double $PAYMENT_DATE
 * @property double $CREATED_ON
 *
 * @property Invoice $invoice
 * @property GroupInvoice $groupInvoice
 */
class GroupInvoiceMap extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%group_invoice_map}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['GROUP_INVOICE_ID', 'INVOICE_ID'], 'required'],
            [['GROUP_INVOICE_ID', 'INVOICE_ID'], 'integer'],
            [['CREATED_ON'], 'number'],
            [['UTR_NO', 'PAYMENT_DATE','BRAND'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'GROUP_INVOICE_MAP_ID' => 'Group  Invoice  Map  ID',
            'GROUP_INVOICE_ID' => 'Group  Invoice  ID',
            'INVOICE_ID' => 'Invoice  ID',
            'UTR_NO' => 'UTR Number',
            'CREATED_ON' => 'Created  On',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert) {
            $this->CREATED_ON = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoice()
    {
        return $this->hasOne(Invoice::className(), ['INVOICE_ID' => 'INVOICE_ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroupInvoice()
    {
        return $this->hasOne(GroupInvoice::className(), ['GROUP_INVOICE_ID' => 'GROUP_INVOICE_ID']);
    }
}
